language: objective-c
rvm: 2.0.0
before_install:
- export LANG=en_US.UTF-8
- gem update cocoapods
- brew update
- brew upgrade xctool
script: xctool -workspace ContinuousIntegrationAtDevCamp.xcworkspace -scheme ContinuousIntegrationAtDevCamp
  -sdk iphonesimulator7.1 clean build test -freshInstall
env:
  global:
    secure: yVfZ0XDSyHC+J9nHO1Q01vr6ja4XB1ZXi42f/ltwV5LBmN1f7BqhG21Cgk3Hxxyy7ESiI3n5pUJ0p8lRwlI5OaXeoCCW2XbgTIRad2ZTEey4Yb3K52+rPKrZS+w+2G9p03tDOrQ1kh1DBrSWYybk96ChfDIC/4te9rI+WclZJow=
